options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - "NETWORK=t2c-dev-vpc"

steps:
# Build and push hyperswitch-vault Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/hyperswitch-vault:$SHORT_SHA', '-t', 'gcr.io/${PROJECT_ID}/hyperswitch-vault:latest', '-f', 'Dockerfile.hyperswitch-vault', '.']
  id: build-hyperswitch-vault

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/hyperswitch-vault:$SHORT_SHA']
  id: push-hyperswitch-vault-short-sha

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/hyperswitch-vault:latest']
  id: push-hyperswitch-vault-latest

# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   id: rolling-action-replace
#   entrypoint: /bin/bash
#   args:
#     - -c
#     - |
#       echo "Checking gcloud version"
#       gcloud version
#       echo "Checking gcloud config"
#       gcloud config list
#       echo "Executing rolling action replace"
#       gcloud compute instance-groups managed rolling-action replace backend-stable-difffusion-us-east1  --region us-east1 --max-surge 4 --max-unavailable 0
#       gcloud compute instance-groups managed rolling-action replace t2c-worker-us-east1  --region us-east1 --max-surge 4 --max-unavailable 0
